"""add reviews table

Revision ID: 8fed705e57ea
Revises: 960ec6564e0d
Create Date: 2026-09-30 13:14:30.771729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fed705e57ea'
down_revision: Union[str, Sequence[str], None] = '960ec6564e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', name='reviewdecision', native_enum=False, length=20), nullable=False),
    sa.Column('damage_type', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('model_damage_type', sa.String(length=10), nullable=True),
    sa.Column('model_severity', sa.String(length=10), nullable=True),
    sa.Column('reviewer', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_report_id'), 'reviews', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_report_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
