"""add issues table

Revision ID: b557705282bd
Revises: 8fed705e57ea
Create Date: 2026-09-30 13:55:00.409705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = 'b557705282bd'
down_revision: Union[str, Sequence[str], None] = '8fed705e57ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('damage_type', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_issues_location', 'issues', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_column('reports', sa.Column('issue_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_reports_issue_id'), 'reports', ['issue_id'], unique=False)
    op.create_foreign_key('reports_issue_id_fkey', 'reports', 'issues', ['issue_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    group_existing_reports()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_issue_id_fkey', 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_issue_id'), table_name='reports')
    op.drop_column('reports', 'issue_id')
    op.drop_geospatial_index('idx_issues_location', table_name='issues', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('issues')
    # ### end Alembic commands ###


def group_existing_reports() -> None:
    """Group the public reports that already exist into issues.

    Same rule as app/services/issues.py at the time of writing (15 m, nearest
    issue, oldest report first). Written in SQL so the migration doesn't depend
    on app code that can change later.
    """
    conn = op.get_bind()
    report_ids = conn.execute(
        sa.text("SELECT id FROM reports WHERE visibility = 'public' ORDER BY created_at")
    ).scalars().all()

    for report_id in report_ids:
        issue_id = conn.execute(
            sa.text("""
                SELECT i.id FROM issues i JOIN reports r ON r.id = :report_id
                WHERE ST_DWithin(i.location, r.location, 15)
                ORDER BY i.location <-> r.location
                LIMIT 1
            """),
            {"report_id": report_id},
        ).scalar()
        if issue_id is None:
            issue_id = conn.execute(
                sa.text("""
                    INSERT INTO issues (id, location, report_count, created_at, last_reported_at)
                    SELECT gen_random_uuid(), location, 0, created_at, created_at
                    FROM reports WHERE id = :report_id
                    RETURNING id
                """),
                {"report_id": report_id},
            ).scalar()
        conn.execute(
            sa.text("UPDATE reports SET issue_id = :issue_id WHERE id = :report_id"),
            {"issue_id": issue_id, "report_id": report_id},
        )

    # count, worst type and worst severity of each issue
    conn.execute(sa.text("""
        UPDATE issues i SET
            report_count = s.report_count,
            last_reported_at = s.last_reported_at,
            damage_type = s.damage_type,
            severity = s.severity
        FROM (
            SELECT
                issue_id,
                count(*) AS report_count,
                max(created_at) AS last_reported_at,
                (array_agg(damage_type ORDER BY CASE damage_type
                    WHEN 'D40' THEN 0 WHEN 'D20' THEN 1 WHEN 'D10' THEN 2
                    WHEN 'D00' THEN 3 ELSE 4 END))[1] AS damage_type,
                (array_agg(severity ORDER BY CASE severity
                    WHEN 'high' THEN 0 WHEN 'medium' THEN 1 WHEN 'low' THEN 2
                    ELSE 3 END))[1] AS severity
            FROM reports
            WHERE issue_id IS NOT NULL
            GROUP BY issue_id
        ) s
        WHERE i.id = s.issue_id
    """))
