"""add report photo deleted at

Revision ID: c4a64dc1cf66
Revises: 19411c61c64c
Create Date: 2026-09-30 14:29:52.517274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a64dc1cf66'
down_revision: Union[str, Sequence[str], None] = '19411c61c64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('photo_deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'photo_deleted_at')
    # ### end Alembic commands ###
