"""add report visibility

Revision ID: e33a9becc1e8
Revises: bb69d0197d47
Create Date: 2026-09-29 19:22:10.931936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33a9becc1e8'
down_revision: Union[str, Sequence[str], None] = 'bb69d0197d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('visibility', sa.Enum('pending', 'public', 'needs_review', 'hidden', name='reportvisibility', native_enum=False, length=20), server_default='pending', nullable=False))
    op.create_index(op.f('ix_reports_visibility'), 'reports', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_visibility'), table_name='reports')
    op.drop_column('reports', 'visibility')
    # ### end Alembic commands ###
